### PR TITLE
Adding wandb integration to text classification, image classification & lm finetuning

### PR DESCRIPTION
**Pull request by rishiraj**
Followed the instructions at [🤗 Trainer](https://huggingface.co/docs/transformers/v4.34.0/en/main_classes/trainer#transformers.TrainingArguments)

### CODE REVIEW

**Review by soumik12345 — COMMENTED** [review]
@rishiraj 
The PR looks good to me. However, we should test out all the pipelines first.
Can you please test the text and image classification pipelines respectively and share the results on this thread?

**Comment by soumik12345** [comment]
@rishiraj Can you please share some sample notebooks to test for these tasks using the cli?

**Comment by rishiraj** [comment]
Successfully integrated WandB with LLM Finetuning, text & image classification. Tests are passing. @soumik12345 Please handle Dreambooth. Here is a notebook I used to test: https://colab.research.google.com/drive/1m0KZzcCuKRn3Rkff32XTvdIfD45hK2Va?usp=sharing

**Review by soumik12345 — CHANGES_REQUESTED** [review]
@rishiraj The changes look good to me. However, I have one feature request:

Currently, all the values of `hub_token` and `push_to_hub` token is being logged to WandB ([ref](https://wandb.ai/rishiraj/huggingface/runs/q5aij16i/overview)) configs which seems to be a breach of security. Please make sure that these values are not logged.

**Review by soumik12345 — APPROVED** [review]
@rishiraj Thanks a lot for the PR.

**Pull request merged**
